[[plugins]]
repo = "vim-jp/vimdoc-ja"

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'powerline/fonts'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'raviqqe/vim-non-blank'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

# [[plugins]]
# repo = "majutsushi/tagbar"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "yuttie/comfortable-motion.vim"

#[[plugins]]
#repo = "w0rp/ale" -> ncoc.vim

[[plugins]]
repo="beanworks/vim-phpfmt"

[[plugins]]
repo = "flyinshadow/php_localvarcheck.vim"

[[plugins]]
repo = "tomasiser/vim-code-dark"

[[plugins]]
repo = "sheerun/vim-polyglot"

[[plugins]]
repo = "iwataka/minidown.vim"

[[plugins]]
repo = "/usr/local/opt/fzf"

[[plugins]]
repo = "junegunn/fzf.vim"

[[plugins]]
repo = "skanehira/translate.vim"

[[plugins]]
repo = "vim-scripts/grep.vim"

[[plugins]]
repo = "Xuyuanp/nerdtree-git-plugin"

[[plugins]]
repo = "osyo-manga/vim-brightest"

#[[plugins]]
#repo = "LeafCage/yankround.vim"
#
#[[plugins]]
#repo = "kien/ctrlp.vim"

[[plugins]]
repo = "cocopon/iceberg.vim"
