command_timeout = 600

[kubernetes]
format = '[($cluster )\($namespace\)](bold green) '
# disabled = false

[gcloud]
format = '[$symbol$project ]($style) '
disabled = true

[php]
format = ""

[nodejs]
format = ""

[python]
format = ""

[docker_context]
format = ""

[golang]
format = "[Go $version](bold cyan) "

[env_var.ENV]
format = "ENV=[$env_value](bold red) "

[env_var.APP_ENV]
format = "APP_ENV=[$env_value](bold red) "

[env_var.PROJECT_ID]
format = "PROJECT_ID=[$env_value](bold red) "

